name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 0.0.1)"
        required: true
        type: string
      message:
        description: "Message to include in the release"
        required: true
        type: string

# Add permissions block
permissions:
  contents: write # Required for creating releases
  packages: write # Required for creating packages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: curl
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Composer validate
        run: composer validate --strict

      - name: PHPUnit
        run: vendor/bin/phpunit --colors=always

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          body: ${{ github.event.inputs.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Packagist
        env:
          USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
          REPO_URL: https://github.com/vemetric/vemetric-php
        run: |
          curl -s -X POST \
            -H 'Content-Type: application/json' \
            -d '{"repository":{"url":"'"$REPO_URL"'"}}' \
            "https://packagist.org/api/update-package?username=${USERNAME}&apiToken=${TOKEN}"
